name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  setup_and_build:
    runs-on: ubuntu-latest
    needs: checkout_code
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn clean install -Dskiptests

  build_docker_image:
    runs-on: ubuntu-latest
    needs: setup_and_build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t school_cloud .

  deploy_to_ec2:
    runs-on: ubuntu-latest
    needs: build_docker_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}

      - name: Deploy Docker image to EC2
        run: |
          docker stop school_cloud || true
          docker rm school_cloud || true
          docker run -d -p 8080:8080 --name school_cloud school_cloud
        env:
          DOCKER_HOST: ssh://${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}
