name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  setup_and_build:
    runs-on: ubuntu-latest
    needs: checkout_code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar-file
          path: target/*.jar
          
  docker:
    runs-on: ubuntu-latest
    needs: setup_and_build
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: nickdk294/school-cloud:1.0

  deploy_to_ec2:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Login to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ~/key.pem
          chmod 400 ~/key.pem

      - name: Deploy image to EC2
        run: |
            sudo docker pull nickdk294/school-cloud:1.0 || true
            if [ "$(docker ps -a -q -f name=school_cloud)" ]; then
              sudo docker stop school_cloud || true
              sudo docker rm school_cloud || true
            fi
            sudo docker run -d -p 80:8082 nickdk294/school-cloud:1.0
         
