name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  setup_and_build:
    runs-on: ubuntu-latest
    needs: checkout_code
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar-file
          path: target/*.jar

  login_to_docker_hub:
    runs-on: ubuntu-latest
    needs: setup_and_build
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build_and_push_image:
    runs-on: ubuntu-latest
    needs: login_to_docker_hub
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: jar-file

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: nickdk294/school-cloud:1.0

  deploy_to_ec2:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - name: Login to EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}

      - name: Deploy Docker image to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY }} ${EC2_USER}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo docker pull nickdk294/school-cloud:1.0 || true
          sudo docker stop school_cloud || true
          sudo docker rm school_cloud || true
          sudo docker run -d -p 80:8082 --name school_cloud nickdk294/school-cloud:1.0
          EOF
